version: "3.0"

services:
  mongo:
    # To create this service, Compose will pull the mongo
    image: mongo:6.0.3
    container_name: mongo
    restart: unless-stopped
    # This tells Compose that we would like to add environment variables
    # from a file called .env, located in our build context.
    # env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=Nghia385685
      - MONGO_INITDB_DATABASE=testdb
    ports:
      - 27017:27017
    volumes:
      # - ./addons/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        # The named volume dbdata will persist the data stored in Mongo’s default data directory, /data/db.
        # This will ensure that you don’t lose data in cases where you stop or remove containers.
      - dbdata:/data/db
    networks: 
      - proxy_network

volumes: 
  dbdata:

networks:
  proxy_network:
    name: proxy_network